steps:
  - name: "node:20"
    entrypoint: "yarn"
    args: ["install", "--production"]

  - name: "node:20"
    entrypoint: "yarn"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
